<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.kanban</groupId>
        <artifactId>kanban-multivista</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <artifactId>kanban-application</artifactId>

    <name>Kanban Application</name>
    <description>Use cases (services), input/output ports, application mappers</description>

    <dependencies>
        <dependency>
            <groupId>com.kanban</groupId>
            <artifactId>kanban-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-context</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-tx</artifactId>
            <scope>provided</scope>
        </dependency>
    </dependencies>
</project>
